### ISSUE TITLE
A Borrower Needs to be able to:

### ISSUE THREAD

**Issue by Hilaryous** [121watts/keevaah#11]

**Comment by timproctor** [comment]
1.have no other loans appearing on loans page if I'm a new user
2.  create a loan that appears on loans page
3.  I have a choice of going to Borrower Dashboard OR All Loans
4. There is a "newest" loan on loans page
5. New loans can pick a category
6. the loans index changes with changes to loans
7. pagination on loans index page

**Comment by timproctor** [comment]
We still need "newest" loan on loans page (4)
and pagination on loans index page (7)

**Comment by Hilaryous** [comment]
decided we don'r really need pagination
